# Ejemplo de la diferencia de cmd vs entrypoint.
FROM ubuntu
# Típico ejemplo de como cambiar el comportamiento, cuando pasameos el comando al contenedor estaremos aplicando el cat.
# en vez del bash.
ENTRYPOINT [ "/bin/cat" ]
